// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseApp() {
  return window['go']['ui']['guiState']['CloseApp']();
}

export function GetWindowSize() {
  return window['go']['ui']['guiState']['GetWindowSize']();
}

export function MinimizeWindow() {
  return window['go']['ui']['guiState']['MinimizeWindow']();
}

export function Run(arg1) {
  return window['go']['ui']['guiState']['Run'](arg1);
}

export function SetWindowSize(arg1, arg2) {
  return window['go']['ui']['guiState']['SetWindowSize'](arg1, arg2);
}

export function ToggleVisibility() {
  return window['go']['ui']['guiState']['ToggleVisibility']();
}
