// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {ui} from '../models';

export function CloseApp():Promise<void>;

export function GetWindowSize():Promise<ui.WindowSize>;

export function MinimizeWindow():Promise<void>;

export function Run(arg1:any):Promise<void>;

export function SetWindowSize(arg1:number,arg2:number):Promise<void>;

export function ToggleVisibility():Promise<void>;
