// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Debug(arg1) {
  return window['go']['ui']['guiState']['Debug'](arg1);
}

export function Error(arg1) {
  return window['go']['ui']['guiState']['Error'](arg1);
}

export function Run(arg1) {
  return window['go']['ui']['guiState']['Run'](arg1);
}

export function Write(arg1) {
  return window['go']['ui']['guiState']['Write'](arg1);
}
