// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseApp():Promise<void>;

export function Debug(arg1:Array<any>):Promise<void>;

export function Error(arg1:Array<any>):Promise<void>;

export function MinimizeWindow():Promise<void>;

export function Run(arg1:any):Promise<void>;

export function ToggleVisibility():Promise<void>;

export function Write(arg1:Array<number>):Promise<number>;
