// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCurrentMetadata() {
  return window['go']['gui']['PlayerControls']['GetCurrentMetadata']();
}

export function GetCurrentMusic() {
  return window['go']['gui']['PlayerControls']['GetCurrentMusic']();
}

export function Mute() {
  return window['go']['gui']['PlayerControls']['Mute']();
}

export function Next() {
  return window['go']['gui']['PlayerControls']['Next']();
}

export function Pause() {
  return window['go']['gui']['PlayerControls']['Pause']();
}

export function Prev() {
  return window['go']['gui']['PlayerControls']['Prev']();
}

export function SetVolume(arg1) {
  return window['go']['gui']['PlayerControls']['SetVolume'](arg1);
}
