// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function GetCurrentMetadata():Promise<model.MusicMetadata>;

export function GetCurrentMusic():Promise<model.Music>;

export function Mute():Promise<void>;

export function Next():Promise<void>;

export function Pause():Promise<void>;

export function Prev():Promise<void>;

export function SetVolume(arg1:number):Promise<void>;
