// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {input} from '../models';

export function Close():Promise<void>;

export function GetInputDevices():Promise<Array<input.InputDevice>>;

export function IsWatching():Promise<boolean>;

export function WatchEvents(arg1:input.InputDevice):Promise<void>;
