// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Close() {
  return window['go']['input']['InputManagerWrapper']['Close']();
}

export function GetInputDevices() {
  return window['go']['input']['InputManagerWrapper']['GetInputDevices']();
}

export function IsWatching() {
  return window['go']['input']['InputManagerWrapper']['IsWatching']();
}

export function WatchEvents(arg1) {
  return window['go']['input']['InputManagerWrapper']['WatchEvents'](arg1);
}
