// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function EventExists(arg1:string):Promise<boolean>;

export function GetEvent(arg1:string):Promise<model.Event>;

export function GetInputDeviceControls():Promise<model.InputDeviceControls>;

export function GetMusicPath(arg1:model.Music):Promise<string>;

export function GetRandomStateMusic(arg1:string):Promise<model.Music>;

export function GetSfxPath(arg1:model.Sfx):Promise<string>;

export function GetState(arg1:string):Promise<model.State>;

export function GetStateMusic(arg1:string,arg2:number):Promise<model.Music>;

export function GetStatePlaylist(arg1:string):Promise<any>;

export function Read(arg1:string):Promise<void>;

export function Save(arg1:string):Promise<void>;

export function SetInputDeviceControls(arg1:model.InputDeviceControls):Promise<void>;

export function StateExists(arg1:string):Promise<boolean>;
