// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function EventExists(arg1) {
  return window['go']['model']['Config']['EventExists'](arg1);
}

export function GetEvent(arg1) {
  return window['go']['model']['Config']['GetEvent'](arg1);
}

export function GetInputDeviceControls() {
  return window['go']['model']['Config']['GetInputDeviceControls']();
}

export function GetMusicPath(arg1) {
  return window['go']['model']['Config']['GetMusicPath'](arg1);
}

export function GetRandomStateMusic(arg1) {
  return window['go']['model']['Config']['GetRandomStateMusic'](arg1);
}

export function GetSfxPath(arg1) {
  return window['go']['model']['Config']['GetSfxPath'](arg1);
}

export function GetState(arg1) {
  return window['go']['model']['Config']['GetState'](arg1);
}

export function GetStateMusic(arg1, arg2) {
  return window['go']['model']['Config']['GetStateMusic'](arg1, arg2);
}

export function GetStatePlaylist(arg1) {
  return window['go']['model']['Config']['GetStatePlaylist'](arg1);
}

export function Read(arg1) {
  return window['go']['model']['Config']['Read'](arg1);
}

export function Save(arg1) {
  return window['go']['model']['Config']['Save'](arg1);
}

export function SetInputDeviceControls(arg1) {
  return window['go']['model']['Config']['SetInputDeviceControls'](arg1);
}

export function StateExists(arg1) {
  return window['go']['model']['Config']['StateExists'](arg1);
}
