// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function RunKeyboardListener() {
  return window['go']['app']['AppState']['RunKeyboardListener']();
}

export function SaveInputControls(arg1) {
  return window['go']['app']['AppState']['SaveInputControls'](arg1);
}

export function SetAudioPlayer(arg1) {
  return window['go']['app']['AppState']['SetAudioPlayer'](arg1);
}

export function SetInputManager(arg1) {
  return window['go']['app']['AppState']['SetInputManager'](arg1);
}
