// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';
import {audio} from '../models';
import {input} from '../models';

export function RunKeyboardListener():Promise<void>;

export function SaveInputControls(arg1:model.InputDeviceControls):Promise<void>;

export function SetAudioPlayer(arg1:audio.Player):Promise<void>;

export function SetInputManager(arg1:input.InputManager):Promise<void>;
